# Generated by Django 5.2.9 on 2025-12-26 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('condition', models.CharField(choices=[('price_above', 'Price Above'), ('price_below', 'Price Below'), ('percent_change', 'Percent Change')], max_length=30)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_window_minutes', models.IntegerField(blank=True, help_text='Used only for percent change alerts', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
